executing
innerExceptionFor: exception
	^exception parameter.